// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZHMu6jxkIx2zZ8MP4p_fzQtxfCZ9wkc',
    appId: '1:988801913759:web:bc4edbd24db25e32df63aa',
    messagingSenderId: '988801913759',
    projectId: 'progetto-prog-mobile-woc',
    authDomain: 'progetto-prog-mobile-woc.firebaseapp.com',
    storageBucket: 'progetto-prog-mobile-woc.firebasestorage.app',
    measurementId: 'G-68ZW9B9R9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1o_C3rZKot4jgZ0PbTtQcqQ5S_z65oiQ',
    appId: '1:988801913759:android:aba1d9727ee3114ddf63aa',
    messagingSenderId: '988801913759',
    projectId: 'progetto-prog-mobile-woc',
    storageBucket: 'progetto-prog-mobile-woc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjHSyJCjKExzFYvcptw3o8pwy-OQgktI0',
    appId: '1:988801913759:ios:d07fb6be326647f5df63aa',
    messagingSenderId: '988801913759',
    projectId: 'progetto-prog-mobile-woc',
    storageBucket: 'progetto-prog-mobile-woc.firebasestorage.app',
    iosBundleId: 'com.example.flutterWoc',
  );
}
